[package]
name = "rle_vec"
version = "0.2.2"
authors = ["Arno Velds <avelds@gmail.com>"]
repository = "https://github.com/veldsla/rle_vec"
homepage = "https://github.com/veldsla/rle_vec"
documentation = "https://docs.rs/rle_vec/"
keywords = ["rle", "vec", "vector", "rlevec"]
categories = ["data-structures"]
license = "MIT"
description = """
A vector like struct that stores data as runs of identical values. Useful for storing sparse data.
"""

[dependencies]
rustc-serialize = "0.3"
